Repository dimigoin/dimigoin-front-v2, pull requests merged in 2020-03, with the labels that each got.

#21 chore(storybook): setup storybook
  .storybook/config.js
  .storybook/main.js
  package.json
  src/components/dimiru/DimiCard.stories.js
  src/components/dimiru/DimiFooter.stories.js
  src/components/dimiru/DimiIcon.stories.js
  yarn.lock
Labels: Documentation, UI Components

#33 chore(ci/cd) : change target branch to develop for testing
  .github/workflows/main.yml
Labels: CI / CD

#35 fix: error in move build directory process
  .github/workflows/main.yml
Labels: Bug, CI / CD

#39 feat(components/dimiru): create DimiButton
  src/components/dimiru/DimiButton.tsx
Labels: UI Components, UI Styling

#43 fix : type for DimiButton / code spelling
  src/components/dimiru/DimiButton.stories.js
  src/components/dimiru/DimiButton.tsx
Labels: Coding style, UI Components

#66 fix : disable action on pull request
  .github/workflows/main.yml
Labels: Bug

#145 fix : add applier in LOAD_CIRCLES
  .eslintrc.js
  package.json
  src/App.tsx
  src/api/axios.js
  src/api/circle/circle.struct.js
  src/api/configureApolloClient.ts
  src/api/index.ts
  src/api/magician.js
  src/components/CircleCard.tsx
  src/interface/circle.ts
  src/pages/Login.tsx
  src/pages/request/CircleApplication.tsx
  src/pages/request/CircleInformation.tsx
  src/utils/error.ts
  src/utils/swal.ts
Labels: Bug
